version: "3"

services:
  nginxproxy:
    depends_on:
      - server
      - client
    image: nginx
    ports:
      - "80:3000"
      - "3001:3001"
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    container_name: server

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    container_name: client
